dist: trusty
sudo: required

before_install:
- apt-get update
- apt-get install python dh-autoreconf build-essential

env:
- VER=2.4.1

install:
- wget https://github.com/singularityware/singularity/releases/download/$VER/singularity-$VER.tar.gz
- tar xvf singularity-$VER.tar.gz
- cd singularity-$VER
- ./configure --prefix=/usr/local --sysconfdir=/etc
- make
- make install
- singularity --version

script:
- singularity --debug run shub://GodloveD/lolcow

