dist: trusty
sudo: required

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq python dh-autoreconf squashfs-tools build-essential

env:
- VER=2.4.1

install:
- wget https://github.com/singularityware/singularity/releases/download/$VER/singularity-$VER.tar.gz
- tar xvf singularity-$VER.tar.gz
- cd singularity-$VER
- ./configure --prefix=/usr/local --sysconfdir=/etc
- make
- sudo make install
- singularity --version

script:
- singularity run shub://GodloveD/lolcow
- singularity pull --name "bids-example.simg" docker://bids/example:latest
- singularity exec bids-example.simg /run.py --help

