dist: trusty
sudo: required

services:
- docker

env:
- VER=2.4.6

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq python dh-autoreconf squashfs-tools build-essential
- docker build -t user/exampledocker .
- docker run -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/output --privileged -t --rm singularityware/docker2singularity user/exampledocker  1> ${HOME}/convert_log.txt
- IMGNAME=$(cat ${HOME}/convert_log.txt  | grep "Done. Image can be found at:" | awk '{ print $7 }' | cut -d / -f 3 | cut -d . -f 1)
- mv ${HOME}/${IMGNAME}.img ${HOME}/user-exampledocker.simg
- ls ${HOME}

install:
- wget https://github.com/singularityware/singularity/releases/download/$VER/singularity-$VER.tar.gz
- tar xvf singularity-$VER.tar.gz
- cd singularity-$VER
- ./configure --prefix=/usr/local --sysconfdir=/etc
- make
- sudo make install
- singularity --version
- cd ${HOME}

script:
- singularity run shub://GodloveD/lolcow  # Test pull/run from Singularity hub
- singularity run user-exampledocker.simg "TESTING... hello, world!"  # Test exec on docker2singularity converted image
# The below is commented since it is currently non-deterministically failing... issue here: https://github.com/singularityware/singularity/issues/1472
#- sudo singularity pull --name "bids-example.simg" docker://bids/example:latest  # Test pull/convert from Docker hub
# - singularity exec bids-example.simg /run.py --help  # Test exec on Docker pulled image

