dist: trusty
sudo: required

before_install:
- wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
- apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
- sudo apt-get update

install:
- sudo apt-get install -y singularity-container
- singularity --version

script:
- singularity --debug run shub://GodloveD/lolcow

